---

- hosts: all
  become: true
  pre_tasks:
  - name: update repo cache (Ubuntu/Debian)
    tags: always,updates
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == Ubuntu

