---

- hosts: all
  become: true
#  vars_files:
#    - secrets.yml
  pre_tasks:
  - name: update repo cache (Ubuntu/Debian)
    tags: always,updates
    apt:
      update_cache: yes
      upgrade: dist
    register: updates_result
    when: ansible_distribution == "Ubuntu"
  tasks:
    - name: Print out rebooting message
      tags: reboot
      debug:
        msg: "Updates applied to {{ inventory_hostname }}, rebooting the system"
      when: updates_result.changed
    - name: Reboot the system
      tags: reboot
      reboot:
      when: updates_result.changed
